using Package.Hangfire;
using Package.Hangfire.Abstractions;
using Package.Identity;
using Package.Logger;
using Package.OpenApi;
using Package.Payments.VnPay;
using Package.Shared.Extensions;
using Package.Shared.Mediator;
using Service.Payment;
using Service.Payment.Services.BackgroundJobs;

var builder = WebApplication.CreateBuilder(args).WithEnvironment<AppSettings>();
var services = builder.Services;
services.AddCoreLogger();
services.AddHttpContextAccessor();
services.AddCoreCors();
services.AddOpenApi(typeof(Program).Assembly);
services.AddCoreMediator(typeof(Program).Assembly);
services.AddCoreIdentity();
services.AddCoreHangfire();
services.AddVnPay();
services.AddScoped<IHangfireScheduleService, TestScheduleService>();

var app = builder.Build();
app.UseCoreExceptionHandler();
app.UseCors(CorsExtensions.AllowAll);
app.UseCoreIdentity();
app.UseOpenApi();
app.UseCoreHangfire();
app.MapGet("/", () => "Service.Payment");
app.Run();