version: "3.8"

volumes:
  minio-data: {}

services:
  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Web UI
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=Password&1234
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data