version: "3.8"

volumes:
  mongodb-data:
    driver: local
  minio-data:
    driver: local

services:
  mongodb:
    container_name: ${COMPOSE_PROJECT_NAME}-mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db
  
  minio:
    container_name: ${COMPOSE_PROJECT_NAME}-minio
    image: quay.io/minio/minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Web UI
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data