version: "3.8"

services:
  mongodb:
    container_name: ${COMPOSE_PROJECT_NAME}-mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-1234qwert}
    volumes:
      - ${PROJECT_DATA_PATH:-${PWD}}/data/mongodb:/data/db
  
  minio:
    container_name: ${COMPOSE_PROJECT_NAME}-minio
    image: quay.io/minio/minio:RELEASE.2025-02-18T16-25-55Z
    ports:
      - "9000:9000" # API
      - "9001:9001" # Web UI
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-1234qwert}
    command: server /data --console-address ":9001"
    volumes:
      - ${PROJECT_DATA_PATH:-${PWD}}/data/minio:/data